test:
  adapter: mysql2
  database: multi_db_test
  username: root
  password:
  host: 127.0.0.1
  pool: 5
  slaves:
    db1:
      adapter: mysql2
      database: multi_db_test
      username: root
      password:
      host: 127.0.0.1
      pool: 5
    db2:
      adapter: mysql2
      database: multi_db_test
      username: root
      password:
      host: 127.0.0.1
      pool: 5
      weight: 10
    db3:
      adapter: mysql2
      database: multi_db_test
      username: root
      password:
      host: 127.0.0.1
      pool: 5
      weight: 5
    otherthing:
      adapter: mysql2
      database: multi_db_test
      username: root
      password:
      host: 127.0.0.1
      pool: 5
      weight: 10
